---

name: github-action-oidc
on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  oidc:
    runs-on: ubuntu-latest
    steps:
      - id: oidc
        run: |
          curl -vvv -H "Accept: application/json; api-version=2.0" -H "Authorization: Bearer ${ACTIONS_ID_TOKEN_REQUEST_TOKEN}" -H "Content-Type: application/json" "${ACTIONS_ID_TOKEN_REQUEST_URL}" > oidc-curl-result.txt

      - uses: actions/upload-artifact@v4
        with:
          name: curl
          path: oidc-curl-result.txt


